- name: Cleanup
  hosts: localhost
  become: true
  tasks:
  - name: Destroy Hub Workers
    shell: |
      virsh undefine hub2_worker1 && virsh undefine hub2_worker2 && virsh undefine hub2_worker3
      virsh destroy hub2_worker1 && virsh destroy hub2_worker2 && virsh destroy hub2_worker3
      rm -f /var/lib/libvirt/images/hub2/hub2_worker1.qcow2 
      rm -f /var/lib/libvirt/images/hub2/hub2_worker2.qcow2 
      rm -f /var/lib/libvirt/images/hub2/hub2_worker3.qcow2 
      rm -f /var/lib/libvirt/images/hub2/storage_worker1.qcow2 
      rm -f /var/lib/libvirt/images/hub2/storage_worker2.qcow2 
      rm -f /var/lib/libvirt/images/hub2/storage_worker3.qcow2 

  - name: Destroy Hub Masters
    shell: |
      virsh undefine hub2_master1 && virsh undefine hub2_master2 && virsh undefine hub2_master3
      virsh destroy hub2_master1 && virsh destroy hub2_master2 && virsh destroy hub2_master3
      rm -f /var/lib/libvirt/images/hub2/hub2_master1.qcow2 
      rm -f /var/lib/libvirt/images/hub2/hub2_master2.qcow2 
      rm -f /var/lib/libvirt/images/hub2/hub2_master3.qcow2 

  - name: Destroy Hub Bootstrap
    shell: |
      virsh undefine hub2_bootstrap  && virsh destroy hub2_bootstrap
      rm -f /var/lib/libvirt/images/hub2/hub2_bootstrap.qcow2 

      #  - name: Destroy Helper VM
      #shell: |
      #virsh undefine helper && virsh destroy helper
      #rm -f /var/lib/libvirt/images/helper_disk.qcow2 

  - name: Cleanup SSH Know Hostss
    shell: |
      rm -f /root/.ssh/known_hosts
