galaxy_info:
  author: sadiquepp
  description: Creates the RBD pool/CephFS filesystem and exports ODF connection details from the Ceph 9 cluster
  license: MIT
  min_ansible_version: "2.9"

dependencies: []
