apiVersion: velero.io/v1
kind: Restore
metadata:
  name: hcp-cluster1-restore
  namespace: openshift-adp
spec:
  backupName: hcp-cluster1-backup
  restorePVs: true
  existingResourcePolicy: update
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io