## ---------------------------------------------------------------------------
## Bootstrap: hand the instances to Ansible.
##
## Terraform is good at making the machines and bad at configuring them, so it
## does not try. It writes an inventory and runs one playbook; everything the
## host needs is expressed there, where it can be re-run on its own without
## touching infrastructure state:
##
##   ansible-playbook -i inventory.ini ansible/bootstrap.yml
##
## Set run_bootstrap = false to do it by hand.
## ---------------------------------------------------------------------------

resource "local_file" "inventory" {
  filename        = "${path.module}/inventory.ini"
  file_permission = "0644"

  content = <<-EOT
    # Generated by terraform. Do not edit - terraform apply overwrites it.
    [metal]
    %{for i, inst in aws_instance.metal~}
    ${inst.tags["Name"]} ansible_host=${inst.public_ip}
    %{endfor~}

    [metal:vars]
    ansible_user=ec2-user
    ansible_ssh_private_key_file=${var.ssh_private_key_path}
    ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null'
    ansible_become=true

    lab_repo_url=${var.repo_url}
    lab_repo_branch=${var.repo_branch}
    lab_base_image_dir=${var.base_image_dir}
    lab_worker_memory=${var.worker_memory}
    lab_worker_cpu=${var.worker_cpu}
    lab_vnc_enabled=${var.vnc_enabled}
  EOT
}

# Waits for the instance to actually accept ssh. A metal instance takes
# several minutes to POST - far longer than a virtualised one - so the
# inventory existing is not the same as the host being reachable, and running
# Ansible too early fails on the first connection rather than on anything
# real.
resource "null_resource" "wait_for_ssh" {
  count = var.instance_count

  triggers = { instance_id = aws_instance.metal[count.index].id }

  connection {
    type = "ssh"
    host = aws_instance.metal[count.index].public_ip
    user = "ec2-user"
    # file() does not expand ~, and ~/.ssh/id_ed25519 is what people write.
    private_key = file(pathexpand(var.ssh_private_key_path))
    timeout     = "15m"
  }

  provisioner "remote-exec" {
    inline = ["cloud-init status --wait || true"]
  }
}

resource "null_resource" "bootstrap" {
  count = var.run_bootstrap ? 1 : 0

  depends_on = [null_resource.wait_for_ssh, local_file.inventory]

  triggers = {
    instances = join(",", aws_instance.metal[*].id)
    playbook  = filemd5("${path.module}/ansible/bootstrap.yml")
  }

  provisioner "local-exec" {
    command     = "ansible-playbook -i inventory.ini ansible/bootstrap.yml"
    working_dir = path.module
  }
}
